### ISSUE TITLE
android 发消息崩溃

### ISSUE THREAD

**Issue by wyasher** [wildfirechat/wfc_flutter_plugins#52]
```
            java.lang.NullPointerException: Attempt to invoke virtual method 'int cn.wildfirechat.message.core.MessageStatus.value()' on a null object reference
                                                                                                    	at cn.wildfirechat.imclient.ImclientPlugin.convertMessage(ImclientPlugin.java:1994)
                                                                                                    	at cn.wildfirechat.imclient.ImclientPlugin.access$200(ImclientPlugin.java:119)
                                                                                                    	at cn.wildfirechat.imclient.ImclientPlugin$9.onPrepare(ImclientPlugin.java:740)
                                                                                                    	at cn.wildfirechat.remote.ChatManager$16.lambda$onPrepared$0$cn-wildfirechat-remote-ChatManager$16(ChatManager.java:2486)
                                                                                                    	at cn.wildfirechat.remote.ChatManager$16$$ExternalSyntheticLambda2.run(Unknown Source:10)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:232)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8159)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
```

**Comment by wyasher** [comment]
环境是flutter 3.10.6
我debug断点试了一下 
```
        map.put("status", protoData.status.value());
```
中protoData.status是不为空的

**Comment by heavyrain2012** [comment]
已解决，提交 https://github.com/wildfirechat/wfc_flutter_plugins/commit/61a045fc3630271f6c3637a30b80f30e4701706c 请更新验证
